{% set name = "mhm" %}
{% set version = "5.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c4244ee58f9c6c20ed9e4d5691132f3f67026992bad48b359f2d44ed7e5d4ef
  patches:
    - no_find_numpy.patch

build:
  skip: true  # [win or (python_impl == 'pypy' and (aarch64 or ppc64le))]
  number: 0
  script_env:
    - SETUPTOOLS_SCM_PRETEND_VERSION={{ version }}
    - MHM_BUILD_PARALLEL=1
    - CMAKE_BUILD_PARALLEL_LEVEL=4
    - SKBUILD_CMAKE_ARGS="-GNinja"
  script:
    - {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - ninja
    - fypp
    - llvm-openmp  # [osx]
    - libgomp      # [linux]

  host:
    - pip
    - python
    - scikit-build-core >=0.5, <0.6
    - setuptools_scm >=7, <8
    - numpy
    - fypp
    - netcdf-fortran

  run:
    - python
    - netcdf-fortran

test:
  commands:
    - mhm -h
    - mhm -V
    - mhm-download -h
    - mhm-download -V
    - mhm-download -v -d 1 -p example_domain
    - mhm example_domain

about:
  home: https://www.ufz.de/mhm
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file:
    - COPYING
    - COPYING.LESSER
    - LICENSE.md
    - AUTHORS
  summary: 'The mesoscale Hydrological Model - mHM'
  description: |
    The mesoscale hydrologic model (mHM) is a spatially explicit distributed
    hydrologic model that uses grid cells as a primary hydrologic unit
    and accounts for the following processes: canopy interception,
    snow accumulation and melting, soil moisture dynamics, infiltration and surface runoff,
    evapotranspiration, subsurface storage and discharge generation,
    deep percolation and baseflow and discharge attenuation and flood routing.
  doc_url: https://mhm.pages.ufz.de/mhm
  dev_url: https://git.ufz.de/mhm/mhm

extra:
  recipe-maintainers:
    - MuellerSeb
    - StephanThober
    - mhm-admin
